### ISSUE TITLE
Use async instead of threading

### ISSUE THREAD

**Issue by temeddix** [cunarist/solsol#85]
This is being developed on a separate branch. Some additional improvements unrelated to async migration are also included.

- https://github.com/cunarist/solie/tree/async-first

## Todo

- [x] Function for handling image downloads
- [x] Avoid using the `time` module
- [x] Remove `threading` imports
- [x] `aiofiles.open()` over `open()`
- [x] Inspect `while True:` expressions
- [x] Remove `undertake()`
- [x] Remove `process_toss` module
- [x] Organize import order
- [x] Integrate Coingecko API
- [x] Fill the status panel
- [x] Properly show the token name
- [x] Remove `dill`
- [x] Stabilize closing
- [x] Selectable log panel
- [x] Fix a problem with `webbrowser` blocking
- [x] `outsource.do()` over `connect()`
- [x] Upgrade Python
- [x] Design a mutex class for resource synchronization
- [x] Find out the reason for performance difference between Windows and macOS(M1)
- [x] Solve the problem where the window becomes unresponsive when closing
- [x] Use the newer version of `qasync` with performance PR applied
- [x] Switch to Poetry

**Comment by temeddix** [comment]
When using `interpreters`(that will be introduced in Python 3.13) in other threads, sharing objects is not possible. We can toss heavy tasks to a separate threadpool, but need to use async for concurrent logic with shared objects.

**Comment by temeddix** [comment]
This PR should be merged for this project to work on Windows properly.

- https://github.com/CabbageDevelopment/qasync/pull/101
